name: publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔨 Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          cache: true
          cache-bin: true

      - name: 🎉 Install project dependencies
        run: bun i

      - name: 🚀 Deploy workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            CHANNEL_ACCESS_TOKEN
            CHANNEL_SECRET
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
